### ISSUE TITLE
Can't use items when in inventory.

### ISSUE THREAD

**Issue by Dunkmania101** [Lanboost/TModLoader_LansUncraftItems#2]
I had been having an issue where I wouldn't be able to use any items when my inventory, but still could when it was closed. After scouring through my settings (The major ones being controls set to mouse 1 and the hotbar lock function), I eventually started disabling mods, trying one at a time. When    I got to this one, the issue appeared again. To clarify, I'm not 100% sure it's this mod's fault, just that it's the issue went away when it wasn't loaded and came back when it was.

Summary: When the mod is enabled, items are only usable when the inventory is closed. Disabling the mod seems to fix the problem.

Sorry if I missed something or formatted this wrong, this is my first issue report.
Thanks!

**Comment by Lanboost** [comment]
Thanks for the time to investigate the issue. This mod definitely had a issue, that when the inventory was open the entire screen click to world, was disabled. This should be fixed with version v1.31.1

Closing the issue, if the issue persist with the new version please feel free to reopen a new ticket!

Regards Lan
